'use strict';

module.exports = [
    {
        namespace: 'goldeconomy',
        recordName: 'GoldEconomy',
        tableClassName: 'TbGoldEconomy',
        tableComment: '金币经济配置表',
        fileName: 'goldeconomy_tbgoldeconomy',
        dataFile: 'goldEconomy.js',
        primaryKey: 'Id',
        fields: [
            { name: 'Id', type: 'int', comment: 'ID' },
            { name: 'DataScale', type: 'int', comment: '配置缩放倍率，统一为10' },
            { name: 'SmallCoinValue', type: 'int', comment: '小金币单枚价值(放大10倍)' },
            { name: 'LargeCoinValue', type: 'int', comment: '大金币单枚价值(放大10倍)' },
            { name: 'GoldPackValue', type: 'int', comment: '金币包单枚价值(放大10倍)' },
            { name: 'RewardRoomGoldMin', type: 'int', comment: '奖励房最低金币产出(放大10倍)' },
            { name: 'RewardRoomGoldMax', type: 'int', comment: '奖励房最高金币产出(放大10倍)' },
            { name: 'NewbieRunGoldMin', type: 'int', comment: '新手局最低金币(放大10倍)' },
            { name: 'NewbieRunGoldMax', type: 'int', comment: '新手局最高金币(放大10倍)' },
            { name: 'StableRunGoldMin', type: 'int', comment: '稳定局最低金币(放大10倍)' },
            { name: 'StableRunGoldMax', type: 'int', comment: '稳定局最高金币(放大10倍)' },
            { name: 'SkilledRunGoldMin', type: 'int', comment: '熟练局最低金币(放大10倍)' },
            { name: 'SkilledRunGoldMax', type: 'int', comment: '熟练局最高金币(放大10倍)' },
            { name: 'HighlightRunGoldMin', type: 'int', comment: '高光局最低金币(放大10倍)' },
            { name: 'HighlightRunGoldMax', type: 'int', comment: '高光局最高金币(放大10倍)' },
            { name: 'TankNoAdGold', type: 'int', comment: '一管体力不看广告金币(放大10倍)' },
            { name: 'TankHalfAdGold', type: 'int', comment: '一管体力半数广告金币(放大10倍)' },
            { name: 'TankFullAdGold', type: 'int', comment: '一管体力全广告金币(放大10倍)' },
            { name: 'DoubleAdNormalThreshold', type: 'int', comment: '双倍广告常规提示阈值(放大10倍)' },
            { name: 'DoubleAdStrongThreshold', type: 'int', comment: '双倍广告强提示阈值(放大10倍)' },
            { name: 'DoubleAdUpgradeGapThreshold', type: 'int', comment: '可立即升级提示差值阈值(放大10倍)' },
        ],
    },
    {
        namespace: 'growthupgrade',
        recordName: 'GrowthUpgrade',
        tableClassName: 'TbGrowthUpgrade',
        tableComment: '成长主表',
        fileName: 'growthupgrade_tbgrowthupgrade',
        dataFile: 'growthUpgrade.js',
        primaryKey: 'Id',
        fields: [
            { name: 'Id', type: 'int', comment: '成长线ID' },
            { name: 'Key', type: 'string', comment: '成长键' },
            { name: 'Name', type: 'string', comment: '成长名称' },
            { name: 'Desc', type: 'string', comment: '成长描述' },
            { name: 'MaxLevel', type: 'int', comment: '最大等级' },
            { name: 'Category', type: 'string', comment: '成长分类' },
            { name: 'ValueType', type: 'string', comment: '效果类型' },
            { name: 'UnlockCondition', type: 'string', comment: '解锁条件' },
            { name: 'DisplayOrder', type: 'int', comment: '显示顺序' },
        ],
    },
    {
        namespace: 'growthupgradelevel',
        recordName: 'GrowthUpgradeLevel',
        tableClassName: 'TbGrowthUpgradeLevel',
        tableComment: '成长等级表',
        fileName: 'growthupgradelevel_tbgrowthupgradelevel',
        dataFile: 'growthUpgradeLevel.js',
        primaryKey: 'Id',
        fields: [
            { name: 'Id', type: 'int', comment: '记录ID' },
            { name: 'UpgradeId', type: 'int', comment: '成长线ID' },
            { name: 'Level', type: 'int', comment: '等级' },
            { name: 'Value', type: 'int', comment: '效果值(放大10倍)' },
            { name: 'CostGold', type: 'int', comment: '升级金币(放大10倍)' },
        ],
    },
    {
        namespace: 'text',
        recordName: 'Text',
        tableClassName: 'TbText',
        tableComment: '文本表',
        fileName: 'text_tbtext',
        dataFile: 'text.js',
        primaryKey: 'Id',
        enumName: 'TextId',
        enumField: 'EnumName',
        enumCommentField: 'ZhCn',
        fields: [
            { name: 'Id', type: 'int', comment: 'ID' },
            { name: 'ZhCn', type: 'string', comment: '中文文本' },
            { name: 'En', type: 'string', comment: '英文文本' },
            { name: 'EnumName', type: 'string', comment: '枚举名称', runtime: false },
        ],
    },
];